services:
  db: 
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - magang-kemnaker-backend:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  app:
    build: .
    container_name: test_backend_kemnaker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      HOST: db
      DB_NAME: testdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      PORT: 8000
      
volumes:
  magang-kemnaker-backend:
    driver: local