# Stage 1: build binary
FROM golang:1.25-alpine AS builder

WORKDIR /app

# Install air untuk auto reload
RUN apk add --no-cache git && \
    go install github.com/air-verse/air@latest

# Copy module files first (for caching dependencies)
COPY go.mod go.sum ./
RUN go mod download

# Copy all source files
COPY . .

# Build the Go binary
# RUN go build -o server .

# # Stage 2: run binary in a clean image
# FROM alpine:3.20

# WORKDIR /app

# # Copy binary dari builder
# COPY --from=builder /app/server .

# Expose API port
EXPOSE 8000

# Run the binary
# CMD ["./server"]
CMD ["air"]